version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=doctorsstudio_crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/doctorsstudio_crm
      - DJANGO_SETTINGS_MODULE=doctorsstudio.settings
      - DJANGO_DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db

volumes:
  postgres_data:
