# Generated by Django 4.2.7 on 2025-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_oauth2token_contact_ghl_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('oauth', 'OAuth'), ('sync', 'Synchronization'), ('system', 'System'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Information'), ('in_progress', 'In Progress')], default='info', max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tokenrequestlog',
            options={'ordering': ['-created_at']},
        ),
    ]
